### ISSUE TITLE
TODO list meta issue

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#1]
Here are some TODO items for a paper.  Normally we keep implementation separate from paper, but it should be fine to put a paper in this repo, since it's just microbenchmarks and sketches at the moment, not a reusable library.

Please update the following when someone claims an issue, and split out into separate issues for discussion as needed.
1. (started by @rrnewton and @chamibuddhika) Manually parallelize the existing bintree microbenchmark.  (Mainly using C.)
   - [x] Introduce offset entries within the packed trees, thus enabling mixed representations and parallelism.
   - [ ] Introduce block-chains for a more realistic allocation story.
   - [ ] Use Cilk for a simple fork-join C implementation.
2. (@rrnewton) finish L1->L2->L3 prototype compiler.  This is the first model of the formal language, and hopefully what will get translated into greek in the paper.
3. (?) Populate a paper skeleton and start filling in the core language for the compiler transforms.
4. (?) Harvest input program(s) for beta-reduction benchmark.  Now moved to issue #4.
5. (?) Manually implement the packed version of a compiler pass in C/C++/Rust.  List of possible passes in #3.
6. (@milindkulkarni & @laithsakka ) Manually implement a packed version of kd-tree for a non-AST example.  See #5.
7. (?) Select other compiler passes and repeat for those.
8. (?) Look into doing a front-end that meshes with a host language.
   - Could be a subset of Haskell + Template Haskell or a preprocessor (e.g. haskell-src-exts).  Could be a core-to-core pass.
   - Could be a very simple DSL in Racket, implemented in a macro but not allowing arbitrary Racket code.  
   - Could be something standalone if we make the **closed world assumption** as described in #2 
## Week-by-week plan for PLDI17 deadline
- Wk1 (10/10): get at least one benchmark AST and a couple manual compiler pass implementations.  Finish translator for minimal core language (2).  Finish (1) above and hopefully (6). 
- Wk2 (10/17): 
- Wk3 (10/24):
- Wk4 (10/31):
- Wk5 (11/7):
- Wk6 (11/14): paper due at start of week Tues, 11/15.
