### ISSUE TITLE
PLDI17 Implementation checklist: Compiler passes and runtime components

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#11]
I'm working on the middle of the compiler.  Here's the basic pipeline.  Check these off when "add1" goes through, and then we'll come back and do a second pass to finish the rest
- [x] Parsing (from Haskell) (@osa1)
- [x] Parsing (from SExp) - we need one or the other of these parsers at 100% functionality
- [x] Effect inference (traversal effects) (@rrnewton)
- [ ] Missing traversal insertion
- [ ] Copy insertion
- [ ] Copy/traversal codegen.  (After this we can actually rerun effect inference and confirm there are no missing traversals.)
- [x] Lowering to target language and cursor insertion.
- [x] C Codegen 

I'm in the middle of hacking on these middle passes.  It's a nano-pass style but most of these are very simple.

And then here are the runtime pieces:
- [x] implementation of SExp parsing for ASTs (@chamibuddhika)
- [x] converting parsed SExps to packed rep, including interning symbols (#6) (@chamibuddhika)
- [x] implementation of dictionary ops (#10)

And other pieces of the implementation:
- [x] Direct implementation of the treelang in Racket (@spall) -- one baseline for benchmarks
- By-hand benchmarks,  other baselines
  -  [x] Write data cleaner (@samth #12)
- [x] Since we're settled on AST format for benchmarks, complete data cleaning (@samth #12)
