### ISSUE TITLE
Dictionaries of packed values

### ISSUE THREAD

**Issue by vollmerm** [iu-parfunc/gibbon#113]
Continuing from #84 and #10 

**Roadmap:**

- [x] Parse simple dictionary operations
- [x] Type-check dictionary operations in front-end language
- [x] Fix pretty-printing of dictionaries
- [x] Extend location inference to cover dictionary operations
- [x] Push dictionaries through mid-end compiler
- [x] Simple approach to adding dictionaries to packed code gen (linked list?)

After these steps are done, we can investigate doing something more sophisticated (ie, fancy data structure in runtime for dictionaries).

**Comment by vollmerm** [comment]
Pushing support for dictionaries through the compiler requires a way of talking about the locations of values that are looked up in the dictionary. For example, if you insert a binary tree into a dictionary, then in some other scope you pull it out, what's the symbolic location of the tree in the second context? 

Conceptually, it's like the location of a function parameter; it's a symbolic location that tells you *nothing*, because the location could be *anything*. 

The first thing I tried, and what's committed now, was extending `letloc` with a new form:

```
letloc l = free in ...
```

This introduces a location with no associated constraints. It says symbolic location `l` is bound in that scope, but nothing is known about `l`. This allows `l` to be used later as the location of the result of a call to `DictLookup`. 

This is just something I came up with out of the blue, and I'm open to alternate suggestions.

**Comment by vollmerm** [comment]
My changes so far allow dictionaries to operate in packed mode and store packed values. 

Still not done, and (I think) outside the scope of this issue is:

- Picking and implementing a fancy data structure
- Integrating dictionaries with memory management
