### ISSUE TITLE
Tracking issue for Gibbon-GHC gaps relevant to Sorting Paper

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#231]
# General issues

- [ ] #223 Recursion Let Expressions
- [ ] #209 Where Expressions

# Issues pertaining to Liquid-Haskell verification

- [ ] delete everything after `?`

# Separate issues for Linear-Haskell compatibility
(LOW PRIORITY)

- [ ] undo CPS-ish code that is there for linear haskell's limitations
