### ISSUE TITLE
Beta branch version 2 - major roadmap/todolist

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#66]
This replaces https://github.com/iu-parfunc/tree-velocity/issues/59.  Our thinking on several of these details has changed.  @vollmerm and I are working on a new formal IR and are building the compiler around it.

The current IR progression we've been discussing has 5 main steps: L1, L2, L2B, L2C, L3.

Feel free to factor any of these out into their own issues and link them here.

### IRs, interpreters, type checkers

* [x] port/implement an L2 type checker that certifies that locations are used correctly (for already anotated programs)

* [x] L2B IR - adds 2nd class location *values*.
* [ ] L2B interp: make sure the interpreter works with `RetE` and explicit location returns/bindings.
* [ ] L2C IR - Remove ReadTag/WriteTag and friends as pattern synonyms and make them proper constructors in a new IR.  L2C will be the 1st to use `CursorTy`/`PtrTy`.

* [ ] Take the current L1.Interp and factor it into a L1/L2 interpreter (pure reduction semantics), and an L2C+ interpreter with store-based reduction semantics.

### Passes

* [x] Update RouteEnds to produce the new L2B.
* [x] Implement a new (location) type inference pass which either succeeds, or fails and gives an error including a hole where a location-conflict occurred.
* [x] Implement a copy-insertion pass that uses type inference in a co-routine manner, inserting copies where failures are found.
* [ ] Implement a new traversal-insert pass that lowers an L2B program to *not* depend on implicit "scroll forward", random-access behavior of case expressions.
* [ ] Port infer-effects to work on a fully-typechecking L2 program. 
* [ ] Implement new, syntax-directed cursorize that converts L2B->L2C.

### Runtime support

* [x] implement the global region (initially) by using Boehm for the fixed-sized objects
* [ ] implement the linked-list-of-pages for the unbounded, growing objects (must choose bounds-check or guard page.. let's make it bounds-check initially).

### Utilities and Misc

* [ ] remove end/start witness convention and attendant code

### Future work

Beyond the scope of this sprint.

 * [x] Implement a region inference pass that infers more precise region lifetimes.
